import fs from 'fs';

const contractList = [
    "Contrato de Aluguel de Imóvel Residencial",
    "Contrato de União Estável",
    "Declaração de União Estável",
    "Contrato de Aluguel de Apartamento",
    "Contrato de Aluguel de Casa",
    "Contrato de Aluguel de Imóvel Comercial",
    "Contrato de Aluguel de Sala Comercial",
    "Contrato de Locação por Temporada",
    "Contrato de Locação de Veículo",
    "Contrato de Compra e Venda de Veículo",
    "Contrato de Promessa de Compra e Venda",
    "Contrato de Compra e Venda",
    "Contrato de Compra e Venda de Imóvel",
    "Contrato de Compra e Venda de Terreno",
    "Contrato de Gaveta de Compra e Venda de Imóvel",
    "Contrato de Compra e Venda de Equipamentos",
    "Contrato de Aluguel",
    "Contrato de Sublocação de Imóvel Comercial",
    "Procuração por Instrumento Particular ou Público",
    "Contrato de Compra e Venda de Empresa/ Ponto Comercial/ Trespasse",
    "Contrato de Locação de Equipamentos e Máquinas",
    "Contrato Social",
    "Contrato de Empréstimo de Dinheiro",
    "Contrato de Prestação de Serviços",
    "Contrato de Trabalho",
    "Contrato de Doação",
    "Contrato de Parceria Empresarial",
    "Contrato de Cessão de Direitos Hereditários",
    "Notificação Extrajudicial no Cartório",
    "Notificação Extrajudicial por Desocupação de Imóvel",
    "Notificação Extrajudicial de Cobrança de Aluguel",
    "Contrato de Arrendamento Rural",
    "Contrato de Arrendamento",
    "Testamento",
    "Contrato de Sublocação de Imóvel Residencial",
    "Contrato de Aluguel de Vaga de Garagem",
    "Contrato de Aluguel/Locação de Espaço para Festas e Eventos",
    "Contrato de Prestação de Serviço Autônomo",
    "Contrato de Prestação de Serviços Advocatícios",
    "Contrato de Prestação de Serviços de Pessoa Física",
    "Contrato de Prestação de Serviço de Construção Civil",
    "Contrato de Prestação de Serviços de Pessoa Jurídica",
    "Contrato de Prestação de Serviços Contábeis",
    "Declaração de Trabalho",
    "Contrato de Trabalho por prazo determinado",
    "Contrato de Trabalho Temporário",
    "Contrato de Jovem Aprendiz",
    "Contrato de Experiência de Trabalho",
    "C­­ontrato de Comodato",
    "Contrato de Arrendamento Comercial/Mercantil/Empresa/Ponto Comercial",
    "Contrato de Prestação de Serviço de Manutenção",
    "Notificação Extrajudicial por condomínio em atraso",
    "Contrato de Prestação de Serviço de Pedreiro",
    "Contrato de Prestação de Serviços Educacionais",
    "Contrato de Prestação de Serviços de Mão de Obra",
    "Contrato de Permuta",
    "Modelo de Revogação de Procuração",
    "Declaração de Residência",
    "Contrato de Empreitada",
    "Autorização de Viagem Nacional/Internacional para Menor (criança ou adolescente)",
    "Recurso contra Multa de Transito",
    "Termo de Confissão de Dívida",
    "Termo de Confidencialidade",
    "Contrato de Franquia",
    "Termo de Cessão de Direitos para Uso de Imagem",
    "Contrato de Cessão de Direitos Autorais",
    "Contrato de Trabalho Intermitente",
    "Contrato de Pacto Antenupcial",
    "Carta de Referência Profissional",
    "Nota Promissória",
    "Declaração de Bens e Valores",
    "Declaração de Rendimentos",
    "Atestado de Comparecimento",
    "Estatuto Social de Associação",
    "Laudo de Vistoria de Veículo",
    "Contrato de Parceria Rural",
    "Contrato de Teletrabalho - Home Office",
    "Contrato de Prestação de Serviço Babysitter",
    "Declaração de Dependentes",
    "Declaração de Inexistência de Bens a Inventariar ou Arrolar",
    "Laudo de Vistoria de Imóvel",
    "Termo de Acordo para Extinção do Contrato de Trabalho",
    "Contrato de Arrendamento de Veículos",
    "Carta de Recomendação para Fins não Profissionais",
    "Declaração de Dissolução de União Estável",
    "Contranotificação Extrajudicial",
    "Contrato de Prestação de Serviço Diarista",
    "Contrato de Compra e Venda de Máquinas",
    "Contrato de Cessão de Carteira de Clientes",
    "Contrato de Compra e Venda de Embarcação",
    "Contrato de Trabalho Rural",
    "Contrato de Prestação de Serviço de Marketing Digital",
    "Contrato de Parceria de Corretagem",
    "Contrato de Namoro",
    "Contrato Sublocação de Espaço para Manicure",
    "Contrato de Licenciamento e Cessão de Propriedade Intelectual",
    "Contrato de Representante Comercial",
    "Contrato de Prestação de Serviço de Cuidador de Idoso ou Enfermeiro Particular (Home Care)",
    "Contrato de Prestação de Serviços de Transporte Escolar",
    "Contrato ou Termo de Adesão",
    "Contrato de Cessão de Direito de Uso Software",
    "Contrato de Prestação de Serviço de Suporte Técnico de Software",
    "Contrato de Desenvolvimento de Software",
    "Contrato de Licença de Software",
    "Contrato de Prestação de Serviços de Freelancer",
    "Contrato de Prestação de Serviços de Personal Trainer",
    "Contrato de Compra e Venda de Aplicativo APPs",
    "Contrato de Estágio",
    "Contrato de Síndico Profissional",
    "Convenção de Condomínio",
    "Contrato de Troca de Bens",
    "Contrato de Prestação de Serviços de Atleta (Trabalho Desportivo)",
    "Contrato de Comissão de Vendas ou Mercantil",
    "Contrato de Comissão de Formatura",
    "Contrato de Atos Constitutivos de EIRELI",
    "Contrato de Consultoria",
    "Contrato de Cessão de Crédito",
    "Contrato de Comissão de Corretagem",
    "Contrato de Trabalho Horista",
    "Contrato de Troca de Bens",
    "Carta de Cobrança",
    "Contrato de Prestação de Serviços para Campanhas Eleitorais",
    "Contrato de Doação para Campanha Eleitoral",
    "Contrato de Locação de Imóvel para Comitê Eleitoral",
    "Contrato de Cooperativa",
    "Contrato de Renúncia de Bens",
    "Contrato de Gestão",
    "Aditivo Contratual",
    "Regimento Interno Condomínio",
    "Contrato de Venda em Consignação de Mercadorias",
    "Contrato de Prestação de Serviços de Transporte",
    "Contrato de Armazenagem de Mercadorias",
    "Contrato de Comissionamento de Intermediação de Negócios",
    "Contrato de Locação de Veículo para Campanha Eleitoral",
    "Contrato de Locação para Terra Rural",
    "Contrato de Comodato de Imóvel Rural",
    "Contrato de Arrendamento Rural para Gado e Pecuária",
    "Contrato de Meeiro Rural",
    "Contrato de Parceria Pecuária de Gado",
    "Contrato de Empreitada Rural",
    "Contrato de Pastoreio Rural",
    "Contrato Trabalho Diarista Rural",
    "Contrato de Cessão de Exploração",
    "Compra e Venda de Materiais de Construção",
    "Contrato de Prestação de Serviço de Engenharia",
    "Contrato de Trabalho Individual de Experiência Empregada Doméstica",
    "Modelo de Substabelecimento de Procuração",
    "Contrato de Mútuo Financeiro",
    "Contrato de doação de sêmen",
    "Contrato de Venda em Consignação",
    "Contrato de Agenciamento",
    "Contrato de Patrocínio Simples",
    "Contrato de Trabalho Cargo de Confiança",
    "Contrato de Parceria de Trabalho",
    "Contrato de Trabalho Voluntário",
    "Contrato de Prestação de Serviços de Formatura",
    "Contrato de Convênio Empresarial",
    "Contrato Joint Venture",
    "Contrato de transferência de dívidas de veículos",
    "Inventário Negativo",
    "Termo de Responsabilidade",
    "Termo de Compromisso de Estágio",
    "Termo de Quitação",
    "Termo de Acordo",
    "Termo de Entrega",
    "Termo de Consentimento",
    "Contrato de Manutenção Industrial",
    "Contrato de Comodato de Equipamento",
    "Contrato de Arrendamento Industrial",
    "Contrato de Prestação de Serviços de Montagem Industrial",
    "Contrato de Locação/Aluguel de Galpão Industrial",
    "Contrato de Prestação de Serviços de AutoEscola",
    "Contrato de Sigilo Industrial",
    "Contrato de Locação/Aluguel de Máquinas Industriais",
    "Contrato de Prestação de Serviços Escolares",
    "Contrato de Arrendamento Rural Para Plantio de Soja",
    "Contrato de Trabalho por prazo Indeterminado",
    "Contrato de Prestação de Serviços de Reforço Escolar ou Monitoria",
    "Contrato de Comodato de Impressora",
    "Contrato de Prestação de Serviços de Bombeiro Civil",
    "Contrato de Prestação de Serviços de Gestor de Tráfego",
    "Contrato de Compra e Venda de Caminhão",
    "Contrato de Compra e Venda de Academia de Ginástica e Musculação",
    "Contrato de Compra e Venda de Roupas",
    "Contrato de Compra e Venda de Trailer de Lanches",
    "Contrato de Prestação de Serviços de Decoração de Casamento",
    "Contrato de Prestação de Serviços Buffet",
    "Contrato de Compra e Venda de Imóvel Inventariado",
    "Contrato de Compra e Venda de Imóvel de Herdeiros",
    "Contrato de Compra e Venda de Lancha",
    "Contrato de Prestação de Serviços de Decoração para Eventos",
    "Contrato de Prestação de Serviços para Atendimento Psicológico",
    "Contrato de Prestação de Serviços de Beleza ou Salão de Beleza",
    "Contrato de Prestação de Serviços Academia e Professor",
    "Contrato de Prestação de Serviço de Curso",
    "Contrato de Compra e Venda de Animais",
    "Contrato de Compra e Venda de Imóvel Rural",
    "Contrato de Prestação de Serviço de Estacionamento Rotativo",
    "Contrato de Aluguel de Brinquedos para Festa Infantil",
    "Contrato de Prestação de Serviços de Zelador de Igreja",
    "Contrato de Prestação de Serviços de Programação",
    "Contrato de Prestação de Serviço Pacote Mensal para Manicure",
    "Contrato de Prestação de Serviços de Microempreendedor Individual (MEI)",
    "Contrato de Prestação de Serviços Food Truck",
    "Contrato de Aluguel de Quarto por Temporada",
    "Contrato de Prestação de Serviços de Segurança",
    "Contrato de Prestação de Serviços Publicitários",
    "Contrato de Aluguel de Consultório Odontológico",
    "Contrato de Parceria com Blogueira",
    "Contrato de Prestação de Serviços para Produção de Vídeo Publicitário",
    "Contrato de Prestação de Serviços para Confecção e Fabricação",
    "Contrato de Prestação de Serviços de Corretagem Imobiliária",
    "Contrato de Prestação de Serviços Salão de Beleza para Noivas",
    "Contrato de Aluguel de Sala para Consultório Psicológico",
    "Contrato de Aluguel de Caminhão",
    "Contrato de Aluguel de Caçamba de Entulho",
    "Contrato de Parceria de Salão e Manicure",
    "Contrato de Parceria entre Advogados",
    "Contrato de Parceria no Instagram",
    "Contrato de Parceria Agrícola",
    "Contrato de Parceria",
    "Contrato de Parceria de Clínica Estética",
    "Contrato de Parceria entre Clínica e Médico ou Dentista",
    "Contrato de Locação de Espaço Publicitário em Muro",
    "Contrato de Aluguel de Espaço para Instalação de Antena",
    "Contrato de Aluguel de Estacionamento",
    "Contrato de Aluguel de Espaço Publicitário em Outdoor",
    "Contrato de Prestação de Serviços de Anúncios Website",
    "Contrato de Aluguel de Toalhas de Mesas",
    "Contrato de Aluguel de Mesas e Cadeiras para Eventos",
    "Contrato de Aluguel de Carrinho de Lanche",
    "Contrato de Aluguel de Kitnet",
    "Contrato de Aluguel de Sala de Aula",
    "Contrato de Aluguel Espaço para Food Truck",
    "Contrato de Prestação de Serviços Digital Influencer",
    "Contrato de Aluguel de Roupas para Festa",
    "Contrato de Locação de Lancha",
    "Contrato de Aluguel de Quarto República",
    "Contrato de Aluguel de Mesa Provençal",
    "Contrato de Aluguel de Cadeira para Salão de Beleza",
    "Contrato de Aluguel de Bens Móveis",
    "Contrato de Aluguel de Imóvel Residencial para Pessoa Jurídica (Igreja Evangélica)",
    "Contrato de Prestação de Serviços de Cobrança",
    "Contrato de Aluguel de Imóvel Comercial (Salão para Igreja Evangélica)",
    "Contrato de Comodato de Veículo",
    "Contrato de Locação de Impressoras",
    "Contrato de Aluguel Built to Suit",
    "Contrato de Locação de Shopping",
    "Contrato de Aluguel de Sítio ou Chácara",
    "Declaração de Aluguel",
    "Declaração de Autônomo",
    "Contrato de Comodato de Imóvel Residencial",
    "Contrato de Comodato de Antena de Internet",
    "Contrato de Comodato para Caseiro que Mora no Sítio ou Chácara",
    "Declaração de Prestação de Serviços",
    "Declaração de Compra e Venda",
    "Declaração de Pagamento",
    "Declaração de Conteúdo Correios",
    "Contrato de Locação de Equipamento de Geração de Energia",
    "Contrato de Consultoria de Marketing",
    "Contrato de Consultoria de Imagem e Estilo",
    "Contrato de Consultoria de Software",
    "Declaração de Estado Civil",
    "Contrato de Compra e Venda de Quotas de Sociedade",
    "Contrato de União Estável",
    "Contrato de Compra e Venda Internacional",
    "Contrato de Aluguel de Veículo para Uber",
    "Contrato de Locação/Aluguel de Terreno",
    "Contrato de Compra e Venda de Bens Móveis",
    "Declaração de Hipossuficiência",
    "Contrato de Mútuo",
    "Contrato de Cessão de Quotas Sociais",
    "Contrato de Cessão",
    "Declaração",
    "Contrato de Compra e Venda de Moto",
    "Contrato de Prestação de Serviços Musicais",
    "Contrato de Prestação de Serviços de Segurança do Trabalho",
    "Contrato de Compra e Venda de Arma",
    "Contrato de Prestação de Serviços Instalação",
    "Contrato de Prestação de Serviços Consultoria",
    "Contrato de Prestação de Serviços de Arquitetura",
    "Contrato de Prestação de Serviços Design Gráfico",
    "Contrato de Prestação de Serviços de Informática",
    "Contrato de Prestação de Serviços de Limpeza",
    "Contrato de Prestação de Serviços de Marcenaria",
    "Contrato de Prestação de Serviços Corretagem de Seguros",
    "Contrato de Prestação de Serviço Médico",
    "Contrato de Prestação de Serviço de Pintura",
    "Contrato de Prestação de Serviços de Fotografia e/ou Filmagem",
    "Contrato de Subarrendamento Rural",
    "Contrato de Arrendamento Rural de Pastagem",
    "Contrato de Cessão de Uso/Posse de Imóvel"
];

const categoryMap: Record<string, string> = {
    'imobiliario_aluguel': 'imobiliario|aluguel|locação|casa|apartamento|terreno|imóvel|sublocação|garagem|shopping|built to suit|sítio|chácara|kitnet|república|condomínio',
    'veiculos_maquinas': 'veículo|carro|moto|caminhão|lancha|barco|embarcação|máquina|equipamento|uber|trânsito',
    'servicos_profissional': 'serviço|freelancer|consultoria|marketing|engenharia|arquitetura|design|manutenção|pedreiro|babysitter|cuidador|diarista|professor|personal|cobrança|segurança|beleza|fotografia|filmagem|médico|dentista|psicológico|escola|aulas|buffet|decoração|eventos|festas|programação',
    'empresarial_parcerias': 'social|empresa|parceria|sociedade|cessão|franquia|joint venture|confidencialidade|nda|startup|eireli|mei|quota|sócio|dívida|patrocínio|agenciamento|representante|comissão|corretagem',
    'trabalhista': 'trabalho|emprego|estágio|jovem aprendiz|experiência|demissão|rescisão|clt|carteira',
    'agronegocio': 'rural|arrendamento rural|gado|pecuária|soja|pastoreio|meeiro|agrícola',
    'familia_pessoal': 'união estável|namoro|divórcio|testamento|doação|pacto antenupcial|viagem|menor|hereditário|inventário|herdeiro|sêmen',
    'docs_rapidos': 'notificação|procuração|declaração|recibo|atestado|carta|laudo|boleto|promissória|confissão|autorização|recurso|termo'
};

const getCategorySlug = (title: string): string => {
    const t = title.toLowerCase();
    for (const [slug, keywords] of Object.entries(categoryMap)) {
        const keywordList = keywords.split('|');
        if (keywordList.some(k => t.includes(k))) {
            return slug;
        }
    }
    return 'docs_rapidos'; // Fallback
};

const generateBatchSQL = (contracts: string[], batchIndex: number) => {
    let sql = `-- Batch ${batchIndex + 1}\n`;

    contracts.forEach(title => {
        const slug = getCategorySlug(title);
        const contractSlug = title.toLowerCase()
            .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '');

        // 1. Insert Contract
        sql += `
INSERT INTO contracts (title, slug, category_id, price, template_body, description, full_description)
VALUES (
    '${title.replace(/'/g, "''")}',
    '${contractSlug}',
    (SELECT id FROM contract_categories WHERE slug = '${slug}'),
    29.90,
    'CONTRATO DE ${title.toUpperCase()}\\n\\nPelo presente instrumento particular, de um lado {{nome_parte_1}}, inscrito no CPF/CNPJ {{doc_parte_1}}, e de outro lado {{nome_parte_2}}, inscrito no CPF/CNPJ {{doc_parte_2}}, resolvem celebrar o presente ${title.toUpperCase()}, mediante as cláusulas e condições abaixo:\\n\\nCLÁUSULA PRIMEIRA - DO OBJETO...\\n',
    'Modelo completo e atualizado de ${title}.',
    'Garanta segurança jurídica com nosso modelo de ${title}, revisado por especialistas e pronto para preenchimento. Inclui cláusulas essenciais e adaptação para diversos cenários.'
) ON CONFLICT (slug) DO NOTHING;
`;

        // 2. Insert Variables (using subquery to get ID)
        sql += `
INSERT INTO contract_variables (contract_id, name, label, type, required, order_index)
SELECT id, 'nome_parte_1', 'Nome da Parte 1', 'text', true, 1 FROM contracts WHERE slug = '${contractSlug}'
UNION ALL
SELECT id, 'doc_parte_1', 'CPF/CNPJ Parte 1', 'text', true, 2 FROM contracts WHERE slug = '${contractSlug}'
UNION ALL
SELECT id, 'nome_parte_2', 'Nome da Parte 2', 'text', true, 3 FROM contracts WHERE slug = '${contractSlug}'
UNION ALL
SELECT id, 'doc_parte_2', 'CPF/CNPJ Parte 2', 'text', true, 4 FROM contracts WHERE slug = '${contractSlug}'
ON CONFLICT DO NOTHING;
`;
    });

    return sql;
};

// Split into batches of 50
const chunkSize = 50;
for (let i = 0; i < contractList.length; i += chunkSize) {
    const chunk = contractList.slice(i, i + chunkSize);
    const sql = generateBatchSQL(chunk, i / chunkSize);
    fs.writeFileSync(`supabase/migrations/2025121719300${i / chunkSize}_mass_import_part_${i / chunkSize + 1}.sql`, sql);
    console.log(`Generated part ${i / chunkSize + 1}`);
}
